drop table if exists groups CASCADE;

drop table if exists users CASCADE;

create table groups
(
    id   integer generated by default as identity,
    name varchar(50),
    primary key (id)
);

create table users
(
    id       integer generated by default as identity,
    created  timestamp,
    logins   integer not null,
    modified timestamp,
    name     varchar(20),
    password varchar(12),
    type     integer not null,
    username varchar(12),
    groupid integer,
    primary key (id)
);